package ua.com.novopacksv.production.model.userModel;

public enum Role {
    ROLE_ADMIN, ROLE_MANAGER, ROLE_ACCOUNTANT, ROLE_TECHNOLOGIST,
    ROLE_STOREKEEPER, ROLE_CMO, ROLE_CTO, ROLE_ECONOMIST, ROLE_CEO, ROLE_FULL_ACCESS
}
